version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  test:
    build:
      context: test
      dockerfile: Dockerfile
    depends_on:
      - api
